### ISSUE TITLE
テストコードが実行できない

### ISSUE THREAD

**Issue by shouh** [shouh/ffphrase#1]
## 現象
```
$ cd
C:\work\github\shouh\ffphrase\ffphrase\test

$ python test_all.py
Traceback (most recent call last):
  File "test_all.py", line 5, in <module>
    from test_argument import *
  File "C:\work\github\shouh\ffphrase\ffphrase\test\test_argument.py", line 5, in <module>
    import argument
ImportError: No module named argument
```

## 原因
テストコードが pyscripter(親ディレクトリを sys.path に追加する) からの実行を前提としているから。詳細は [PyScripter は sys.path にプロジェクトのルートパスを追加する - shouhの日記](http://d.hatena.ne.jp/shouh/20140112/1389485566) を参照。

…要するに **pyscripter で test_all.py を実行した時しか実行できない** 。

## 対処方法
テストコードを書き直して(import文あたりか？)親ディレクトリのテスト対象コードをimportできるようにする。

**Comment by shouh** [comment]
# メモ
## 相対パスのimport
http://www.lifewithpython.com/2015/05/python-import.html によると
* `__init__.py` 作っておけば import 文で相対パスが使える
* `__init__.py` を使いたくない場合, sys.path に頑張って所望のパスを追加しなさい(推奨はされていない)

http://d.hatena.ne.jp/chlere/20110618/1308369842 によると
* なんか `__init__.py` の中にも import 文を書かないといけない
* Pythonは「現在実行されているファイルをモジュールのルートと見なす」という仕様
  * ルートより上層のディレクトリはインタプリタからは見えないため import 不可
* **うー、python の import 文の仕様がようわからん** 。どうなっとんじゃ。単に自身のファイルからの相対パス指定で済ませたいんだが、なぜそんなシンプル仕様じゃないんやろう？

**Comment by shouh** [comment]
## 対処
PYTHONPATH 手動追加による運用回避。
